services:
  groupgardenbot:
    container_name: groupgardenbot
    image: birabittoh/groupgardenbot
    build:
      context: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
